version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@db:5432/express_template
      - JWT_SECRET=production-jwt-secret-change-me
      - BCRYPT_ROUNDS=12
      - BASIC_AUTH_USERNAME=admin
      - BASIC_AUTH_PASSWORD=secure-admin-password
      - CORS_ORIGIN=http://localhost:3000
      - LOG_LEVEL=info
      - LOG_PRETTY=false
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=express_template
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
